### ISSUE TITLE
Run through LDN Test Suite

### ISSUE THREAD

**Issue by csarven** [Lukkie/LinkedDataNotificationWatcher#1]
It'd be great to see this pass the tests at https://linkedresearch.org/ldn/tests/ - perhaps as an LDN Consumer? - so that we can see it at https://linkedresearch.org/ldn/tests/summary :)

**Comment by Lukkie** [comment]
Hi @csarven 

First of all, loved your work regarding Linked Data Notifications, dokieli etc. It really helped me out during my thesis :)

To answer your request: I doubt this tool is production-ready. It was developed within a tight timeframe to fulfill a single task. It does not do inbox or notification discovery because adding these to the command-line parameters was faster in my case. The only test that would pass is the NA test, since it does look for _announce_ notifications.

I think it would be better to exclude this script from your tests ;)

**Comment by csarven** [comment]
I understand, no worries.

Glad to hear that some of the work were useful in your thesis. I'll have a closer look at your thesis; I might actually be able to cite some of your evaluation in my thesis ;)

**Comment by csarven** [comment]
@Lukkie Can I reach you over email or IM re questions about your thesis?

**Comment by Lukkie** [comment]
@csarven Yeah sure! You can reach me at vanhouckelukas@gmail.com
